### ISSUE TITLE
setup.sh appears Mac-OSX specific, name it appropriately

### ISSUE THREAD

**Issue by homberghp** [sebivenlo/jenkins#1]
Hi Guys,

The setup.sh is pretty useless for me (Linux user), because I do not need nor have docker-machine.
So it would be nice to add a Linux variant for the script and maybe name the current version `setup.sh`,
or maybe ask what OS you are on and then do your thing.

I do not thick Windows users can use the setup file either.

**Comment by holgerkemper** [comment]
Hello hom,

sorry for this inconvenience, but as we already wrote in the readme, this workshop is based on another tutorial and the setup.sh is a left over of it. So, please ignore it and just run the docker-compose command.
